# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, visualizacion ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint || echo "No se ha configurado eslint todavía"
      - name: Build
        run: npm run build
